### DISCUSSION TITLE
代码高亮

### DISCUSSION THREAD

**Discussion by SoHotLB** [YunYouJun/yunyoujun.github.io#144] [Q&A]
博主，为啥我参考你的_config.yml和_config.yun.yml文件，但是代码不高亮呀
![20220911155152-2022-09-11-15-51-52](http://lbbuket-blog.oss-cn-hangzhou.aliyuncs.com/blog-img/20220911155152-2022-09-11-15-51-52.png/w800)

![20220911155319-2022-09-11-15-53-19](http://lbbuket-blog.oss-cn-hangzhou.aliyuncs.com/blog-img/20220911155319-2022-09-11-15-53-19.png/w800)

**Comment by YunYouJun** [comment]
代码高亮符号是 三个反引号。\`\`\`

**Reply by SoHotLB** [reply]
这个知道，可能我图片像素比较低，是使用的三个反引号

**Reply by YunYouJun** [reply]
检查是否开启代码高亮。

https://yun.yunyoujun.cn/guide/config.html#%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE

**Reply by SoHotLB** [reply]
没错，我就是看的这，这是我博客地址：http://bbstudy.net/。可以辛苦帮我看看嘛（可怜）

**Reply by YunYouJun** [reply]
请提供仓库源代码地址。

**Reply by SoHotLB** [reply]
https://github.com/SoHotLB/SoHotLB.github.io/tree/master

**Reply by YunYouJun** [reply]
样式没有正常引入。

<img width="703" alt="image" src="https://user-images.githubusercontent.com/25154432/190234465-e4e3ae1d-b6ee-42a5-9e17-1dca6e1a272b.png">

移除 `_config.yun.yml` 中 `cdn` 字段可解决。

```yml
cdn:
  # pre: https://cdn.jsdelivr.net/gh/SoHotLB/SoHotLB.github.io@main
  pre: ''
  css:
  js:
    base:
    async:
      # 默认引入的图标资源，使用 iconfont
      iconfont: //at.alicdn.com/t/font_1140697_dxory92pb0h.js
    defer:
```

这里你看起来是直接从主题拷贝了一份全部的配置，这会覆盖更新后的主题配置。
只需要按需配置自己需要的配置就可以了，主题会自动和默认配置进行合并的。
